//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteChoThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHopDong
    {
        public ChiTietHopDong()
        {
            this.PhieuDenBu = new HashSet<PhieuDenBu>();
        }
    
        public string MaXe { get; set; }
        public string MaHopDong { get; set; }
        public System.DateTime NgayGiaoXe { get; set; }
        public System.DateTime NgayTraXe { get; set; }
        public double ThanhTien { get; set; }
        public string HienTrang { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual Xe Xe { get; set; }
        public virtual ICollection<PhieuDenBu> PhieuDenBu { get; set; }
    }
}
