//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteChoThueXe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebChoThueXeEntities : DbContext
    {
        public WebChoThueXeEntities()
            : base("name=WebChoThueXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietHopDong> ChiTietHopDong { get; set; }
        public DbSet<ChiTietPhieuDenBu> ChiTietPhieuDenBu { get; set; }
        public DbSet<ChiTietThanhToan> ChiTietThanhToan { get; set; }
        public DbSet<HangXe> HangXe { get; set; }
        public DbSet<HoaDon> HoaDon { get; set; }
        public DbSet<HopDong> HopDong { get; set; }
        public DbSet<KhachHang> KhachHang { get; set; }
        public DbSet<NhaCungCap> NhaCungCap { get; set; }
        public DbSet<PhieuDenBu> PhieuDenBu { get; set; }
        public DbSet<PhuongThucThanhToan> PhuongThucThanhToan { get; set; }
        public DbSet<TaiKhoan> TaiKhoan { get; set; }
        public DbSet<Xe> Xe { get; set; }
    }
}
