//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteChoThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangXe
    {
        public HangXe()
        {
            this.Xe = new HashSet<Xe>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
    
        public virtual ICollection<Xe> Xe { get; set; }
    }
}
