//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteChoThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.ChiTietPhieuDenBu = new HashSet<ChiTietPhieuDenBu>();
            this.ChiTietThanhToan = new HashSet<ChiTietThanhToan>();
        }
    
        public string SoHoaDon { get; set; }
        public string MaHopDong { get; set; }
        public double TongTien { get; set; }
        public System.DateTime NgayLap { get; set; }
    
        public virtual ICollection<ChiTietPhieuDenBu> ChiTietPhieuDenBu { get; set; }
        public virtual ICollection<ChiTietThanhToan> ChiTietThanhToan { get; set; }
        public virtual HopDong HopDong { get; set; }
    }
}
