//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteChoThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public HopDong()
        {
            this.ChiTietHopDong = new HashSet<ChiTietHopDong>();
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public string MaHopDong { get; set; }
        public string MaKhachHang { get; set; }
        public System.DateTime NgayLap { get; set; }
        public double TongTien { get; set; }
    
        public virtual ICollection<ChiTietHopDong> ChiTietHopDong { get; set; }
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
