//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteChoThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuongThucThanhToan
    {
        public PhuongThucThanhToan()
        {
            this.ChiTietThanhToan = new HashSet<ChiTietThanhToan>();
        }
    
        public string MaThanhToan { get; set; }
        public string TenPhuongThucThanhToan { get; set; }
    
        public virtual ICollection<ChiTietThanhToan> ChiTietThanhToan { get; set; }
    }
}
