//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteChoThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.KhachHang = new HashSet<KhachHang>();
            this.NhaCungCap = new HashSet<NhaCungCap>();
        }
    
        public string MaTaiKhoan { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<KhachHang> KhachHang { get; set; }
        public virtual ICollection<NhaCungCap> NhaCungCap { get; set; }
    }
}
