//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteChoThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        public Xe()
        {
            this.ChiTietHopDong = new HashSet<ChiTietHopDong>();
        }
    
        public string MaXe { get; set; }
        public string MaHang { get; set; }
        public string TenXe { get; set; }
        public string MauXe { get; set; }
        public double GiaThue { get; set; }
        public int NamSanXuat { get; set; }
        public string BienSoXe { get; set; }
        public string AnhXe { get; set; }
        public int TinhTrang { get; set; }
        public string MoTa { get; set; }
        public string HienTrang { get; set; }
        public int SoLanThue { get; set; }
        public string MaNhaCungCap { get; set; }
        public int SoChoNgoi { get; set; }
    
        public virtual ICollection<ChiTietHopDong> ChiTietHopDong { get; set; }
        public virtual HangXe HangXe { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
